// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30ZOp_L2Q3sqTYHeF_aKsx3w6peI8p70',
    appId: '1:811951492756:web:8a48191f4cc0afff00ee81',
    messagingSenderId: '811951492756',
    projectId: 'spotify-d850a',
    authDomain: 'spotify-d850a.firebaseapp.com',
    storageBucket: 'spotify-d850a.appspot.com',
    measurementId: 'G-9SZVTBZ975',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5TvsD-WoGWd_c2UoVtqixix6VHWBG-SA',
    appId: '1:811951492756:android:2ab4305aa61a9a3200ee81',
    messagingSenderId: '811951492756',
    projectId: 'spotify-d850a',
    storageBucket: 'spotify-d850a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNpWXwMq61dr7Pjd9gmi7n5e4w1k5QZA',
    appId: '1:811951492756:ios:7037c6cb1db2e61d00ee81',
    messagingSenderId: '811951492756',
    projectId: 'spotify-d850a',
    storageBucket: 'spotify-d850a.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACNpWXwMq61dr7Pjd9gmi7n5e4w1k5QZA',
    appId: '1:811951492756:ios:7037c6cb1db2e61d00ee81',
    messagingSenderId: '811951492756',
    projectId: 'spotify-d850a',
    storageBucket: 'spotify-d850a.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB30ZOp_L2Q3sqTYHeF_aKsx3w6peI8p70',
    appId: '1:811951492756:web:dc82aae9d089ee9500ee81',
    messagingSenderId: '811951492756',
    projectId: 'spotify-d850a',
    authDomain: 'spotify-d850a.firebaseapp.com',
    storageBucket: 'spotify-d850a.appspot.com',
    measurementId: 'G-8BCWYC5Z2H',
  );
}
